version: '3.8'

services:
  backend:
    image: docker.io/naglissul/bankas-skafis-api:latest
    ports:
      - "9000:9000"
    environment:
      - FIREBASE_SERVICE_ACCOUNT_PATH=/etc/secrets/firebase-admin.json
      - FIREBASE_REALTIME_DB_URL=https://bankas-skafis-default-rtdb.europe-west1.firebaseio.com
      - ENVIRONMENT=dev
      - PORT=9000
      - SENTRY_AUTH_TOKEN=your-sentry-auth-token
    volumes:
      - /local/path/to/firebase-admin.json:/etc/secrets/firebase-admin.json
