name: Trigger every 20 minutes part 1
#need two cronjobs, cuz minimum is every 15 minutes
on:
  schedule:
    - cron: "0,20,40 * * * *"

jobs:
  send_requests:
    runs-on: ubuntu-latest

    steps:
      - name: Send HTTP GET request to trigger 1
        run: |
          curl -X GET "https://api.bankas.skafis.lt/misc/triggerService"
