name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u naglissul --password-stdin

      - name: Build Docker image
        run: docker build -t naglissul/bankas-skafis-api:latest .

      - name: Push Docker image to DockerHub
        run: docker push naglissul/bankas-skafis-api:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Render deployment
        run: |
          curl https://api.render.com/deploy/${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_HOOK_KEY }}
